addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.github.sbt"      % "sbt-pgp"      % "2.1.2")
